### ISSUE TITLE
Is Nexus GraphQL.js compatible?

### ISSUE THREAD

**Issue by gunar** [prisma/nexus#106]
I'm trying to stitch together Nexus and [graphql-sequelize](https://github.com/mickhansen/graphql-sequelize/), and I'm having trouble. As I understand, the latter exposes [`graphql`](https://github.com/graphql/graphql-js) compatible object, and I can't use it as input for `nexus`.

Or is there a way to do it?

**Comment by gunar** [comment]
Dupe #88

**Comment by blazestudios23** [comment]
I'm trying to do the same, and don't see any real data on how this is done. I would love to hear back.

**Comment by tgriesser** [comment]
See #983 / `1.2.0-next.14` for better support here
