### ISSUE TITLE
Type information is lost for scalar types

### ISSUE THREAD

**Issue by schuma7** [prisma/nexus#113]
I'm using various scalars from the @okgrow/graphql-scalars package, such as:

`const NonNegativeIntScalar = asNexusMethod(NonNegativeInt, 'nonNegativeInt');`

Applying such a scalar to a field using:

`t.nonNegativeInt('totalCount');`

will produce an "any" type in the resulting typescript file, instead of the more specific "number":

`totalCount: any; // NonNegativeInt!`

I wanted to ask if there might be a way to provide a type hint when creating the scalar, for example like this: `asNexusMethod(NonNegativeInt, 'nonNegativeInt', { targetType: 'number' });`

It'd be great if this type information doesn't get lost when working with scalars. Since it's quite an overhead to manually specify all these types and merging them with typegenAutoConfig.

**Comment by tgriesser** [comment]
> It'd be great if this type information doesn't get lost when working with scalars. Since it's quite an overhead to manually specify all these types and merging them with typegenAutoConfig.

Have you seen the [backingTypeMap](https://github.com/prisma/nexus/blob/1679e4c1ae0be7a00e15ba20c63fad9bd0080516/examples/ghost/src/ghost-schema.ts#L24-L26) option of `typegenAutoConfig`. Makes it a little simpler to specify them manually, and I believe it should do what you're looking for.

I do like the idea of adding the `targetType` or similar though to provide this as runtime info. Would like some better options for runtime type specification in general (see #17).

**Comment by schuma7** [comment]
I have indeed missed the backingTypeMap option and managed to get it to work using the following options:

```
const schema = makeSchema({
  types: [Query, collectionSchema, commonSchema, companySchema],
  outputs: {
    schema: path.join(__dirname, '..', 'schema.graphql'),
    typegen: path.join(__dirname, 'generated', 'nexus-typegen.ts'),
  },
  typegenAutoConfig: {
    contextType: 'common.Context',
    sources: [
      {
        alias: 'common',
        source: path.join(__dirname, 'common', 'commonTypes.ts'),
      },
    ],
    backingTypeMap: {
      NonNegativeInt: 'number',
    },
  },
});
```

This is not directly related to the initial issue, however, when running the compiled version in the dist directory, Nexus prints the following message:
"GraphQL Nexus: Unable to find file or module /Users/user/project/dist/common/commonTypes.ts, skipping
Missing required typegen import: common"

I've used the approach from the ghost example, have I missed something here?

**Comment by tgriesser** [comment]
Yep, the issue is that your `makeSchema` file is in `/src` which gets compiled to `dist` starts up from there, and you're looking for `commonTypes.ts` which doesn't exist. You either want the `.d.ts` (assuming you're outputting those):

```
path.join(__dirname, 'common', 'commonTypes.d.ts'),
```

or the `.ts` that is up a directory in `src`

```
path.join(__dirname, '../src/common', 'commonTypes.ts'),
```

**Comment by schuma7** [comment]
One should clearly restrain from late night coding ;-). Thanks for your help!

Btw, I'm really enjoying the DX so far, great work!
