### ISSUE TITLE
Nexus inefficiences with queries?

### ISSUE THREAD

**Issue by mwest-im** [prisma/nexus#116]
Background: My team and I have recently implemented prisma-nexus and are seeing inefficient querying happening. I'm not sure if this has to do with the prisma implementation of the nexus code, or the underlying code itself. 

I've posted a (potential) bug on that project here:
prisma/nexus-prisma#239

Problem: I'm seeing nexus breaking up one query (as passed through apollo or yoga) being broken up into multiple queries. In almost all cases this is causing multiple inefficient queries being run. I go into more details in my other post, but the gist is that the nexus-generated queries query for more properties than needed and repeat for the number of records they are querying against. Here's a simplified example:

Here's the schema:
`type User {`
`  id: ID`
`  email: String`
`  name: String`
`  posts: [Post]`
`}`

`type Post {`
`  id: ID!`
`  createdAt: DateTime`
`  updatedAt: DateTime`
`  published: Boolean`
`  title: String`
`  type:PostType`
`  content: String`
`  author: User`
`}`

`enum PostType{`
`AUTO`
`MANUAL`
`}`

Let's say I have 2 Users and 3 posts in the DB. 
When running this query:
`{`
`posts(where:{}){id author{id}}`
`}`

It results in 3 queries sent to prisma. One query for each post. And the queries are for all the properties on both `types`.
Example of nexus-generated query:
`{"query":"query ($where: PostWhereUniqueInput!) {`
  `post(where: $where) {`
    `author {`
      `id`
      `email`
      `name`
    `}`
  `}`
`}`
`","variables":{"where":{"id":"cjujykxsx00270708hyu8rt4d"}}},{"query":"query ($where: PostWhereUniqueInput!) {`
  `post(where: $where) {`
    `author {`
      `id`
      `email`
      `name`
    `}`
  `}`
`}`
`","variables":{"where":{"id":"cjujyv7tb00370708vdqvwa49"}}},{"query":"query ($where: PostWhereUniqueInput!) {`
  `post(where: $where) {`
    `author {`
      `id`
      `email`
      `name`
    `}`
  `}`
`}`
`","variables":{"where":{"id":"cjuk7told007l07441076g6rs"}}},{"query":"query ($where: PostWhereUniqueInput!) {`
  `post(where: $where) {`
    `author {`
      `id`
      `email`
      `name`
    `}`
  `}`
`}`
`","variables":{"where":{"id":"cjuk7w4s300a30744rwmj4nwt"}}}`

As you can see - very inefficient. There are also issues with querying enums as well. 

I don't know if it's the nature of nexus (or nexus-prisma) to break up the query, but it seems like there's definitely an issue here. Any ideas?

**Comment by tgriesser** [comment]
This sounds like an issue for the [nexus-prisma](https://github.com/prisma/nexus-prisma) library - as nexus doesn't have any opinions about how your queries are generated, feel free to open there.

**Comment by mwest-im** [comment]
> This sounds like an issue for the [nexus-prisma](https://github.com/prisma/nexus-prisma) library - as nexus doesn't have any opinions about how your queries are generated, feel free to open there.

Great. That's what I wasn't sure of. Thanks for clarifying.
