### ISSUE TITLE
Autocomplete on prismaFields not working following blog example

### ISSUE THREAD

**Issue by AndrewMorsillo** [prisma/nexus#117]
I'm following the example from the blog post https://www.prisma.io/blog/using-graphql-nexus-with-a-database-pmyl3660ncst

I don't get any autocompletion for the array of prismaFields as shown in the blog. TS correctly identifies when I have an invalid array item but it does not autocomplete the values. I'm using webstorm 2019.1 and TS 3.4.4. 

Also the blog post is a bit out of date, using a string value `"false"` for the default of the published field when the latest version of prisma expects `false`.

**Comment by tgriesser** [comment]
Not sure, might want to open this as an issue on https://github.com/prisma/nexus-prisma
