### ISSUE TITLE
Use only "string" reference

### ISSUE THREAD

**Issue by steida** [prisma/nexus#121]
It is weird that Nexus provides two ways for the same task. Sooner or later schema has to be split to files, and then non-string reference does not make sense. 

```
export const SignInErrors = objectType({
  name: 'SignInErrors', // Allow only string here.
```

Does it make sense?

**Comment by tgriesser** [comment]
The main idea here was that by allowing object references it provides a better experience for IDEs that support features like jump-to-definition, unfortunately I haven't been able to get that to work a similar way with just strings. 

So really it's up to however you want to use it I suppose, if you want to only use strings you're more than welcome to do it that way.

**Comment by steida** [comment]
I see. Thank you for the answer, that makes sense.
