### ISSUE TITLE
how to support something like a date / dateTime arg?

### ISSUE THREAD

**Issue by chrisdrackett** [prisma/nexus#122]
I'm moving over to nexus and so far I'm pretty happy with it. However I've run into something I'm confused about around args that are not provided by nexus. For example I have the following:

```
    t.field('setDeleted', {
      type: 'Task',
      args: {
        id: idArg({ required: true }),
        deletedAt: stringArg({ required: true }),
      },
      resolve: (_parent, { id, deletedAt }, ctx) => {
        return ctx.prisma.updateTask({
          where: { id },
          data: { isDeleted: true, deletedAt: deletedAt },
        })
      },
    })
```

However with this I get an error: `Variable "$deletedAt" of type "DateTime!" used in position expecting type "String!".`

so I'm curious how to support an arg type that isn't provided by nexus.

**Comment by tgriesser** [comment]
You can use the `arg` and create little helpers for these as you see fit (assumes `DateTime` is available as a custom scalar):
```ts
const dateTimeArg = (opts) => arg({ ...opts, type: "DateTime" })
```

**Comment by chrisdrackett** [comment]
ok, thanks, any help on what the type for `opts` would be?

**Comment by tgriesser** [comment]
Yep, that or this should work:
```ts
import { arg, core } from 'nexus'
const dateTimeArg = (
  opts: core.NexusArgConfig<'DateTime'>
) => arg({ ...opts, type: "DateTime" })
```

Really the only difference is the type for the `default` value.
