### ISSUE TITLE
Root `Query` type should not be required when we use queryField

### ISSUE THREAD

**Issue by steida** [prisma/nexus#132]
When we use queryField only, Nexus should not warn about: Nexus: You should define a root `Query` type for your schema

Am I correct?

**Comment by unmyke** [comment]
I face the same problem: I create field for queries and pass it to makeSchema, but there is no Query type in generated schema.graphql. So, I create empty Query type:

```javascript
export const Query = queryType({
  definition() {},
});
```

and add it to "types" array prop of makeSchema argument before fields generated by queryField.
