### ISSUE TITLE
Process for creating apollo fullstack example

### ISSUE THREAD

**Issue by idkjs** [prisma/nexus#133]
I am looking at your https://github.com/prisma/nexus/tree/develop/examples/apollo-fullstack example. 

I cant figure out what commands you used to generate the project. Can you shed any light on that?

Thank you.

**Comment by tgriesser** [comment]
`npm start` should start the server and generate the types/graphql assets. Otherwise the rest of the code was adapted from https://github.com/apollographql/fullstack-tutorial
