### ISSUE TITLE
throwing errors

### ISSUE THREAD

**Issue by aTylerRice** [prisma/nexus#135]
I am trying to return some error codes for a custom resolver.

As part of my mutations:
``` 
t.field('login', {
      type: AuthPayload,
      args: {
        email: stringArg(),
        password: stringArg(),
      },
      resolve: async (parent, { email, password }, context) => {
        return login(email,password);
      },
    })
```

inside of login an error is thrown like:
`throw new Error('Login failed');`

How do I get nexus to handle this error so that it comes back in graphql errors array?

**Comment by israelglar** [comment]
As I understand it's not `nexus` jobs to handle errors. What handles resolver errors is the graphql server that you are using (apollo, yoga, etc...).
See `formatError` option:
Apollo: https://www.apollographql.com/docs/apollo-server/api/apollo-server#apolloserver
Yoga: https://github.com/prisma/graphql-yoga/#startoptions-options-callback-options-options--void----null-promisevoid

In my case I'm using Yoga and when one of my resolvers throws an error, it handles automatically and fowards to the user :+1:  Hope that helps!

**Comment by jasonkuhrt** [comment]
@israelglar explained the situation correctly. Nexus today assumes you will be running with Apollo Server. If that changes in the future we could revisit the topic of error handling as a new feature. But that is not on the current roadmap.

**Comment by heymartinadams** [comment]
Read through the comments above, and understand that it’s not `nexus`’ job to handle errors. However, as I have it currently set up with `graphql-yoga`, using `nexus` actually interferes with error handling: when I throw an error, nothing ends up getting returned from the resolver, which therefore throws a _superimposed_ error such as `Cannot return null for non-nullable field Mutation.authCodeVerify`.

The logger still shows the `Incorrect verification code` error, but it then is immediately followed by the `Cannot return null for non-nullable field Mutation.authCodeVerify` error.

## Example
```js
// Packages
import { intArg, stringArg } from 'nexus'

export default {
  // nullable: true,
  type: 'User',
  args: {
    authCode: intArg({ nullable: false }),
    mobile: stringArg({ nullable: false })
  },
  resolve: async (parent, { authCode, mobile }, { photon }, info) => {
    // Get user by auth code and mobile
    const users = await photon.users.findMany({ where: { AND: [{ authCode }, { mobile }] } })

    if (users.length === 0) {
      throw new Error('Incorrect verification code')
    }

    return users[0]
  }
}
```

**Comment by heymartinadams** [comment]
Ah! Sorry, the above happened because I actually had had a `try {...} catch(err) {...}` inside my resolver. Once I removed it, error handling once again worked. So please disregard.
