### ISSUE TITLE
Is it possible to have a script to generate the schema?

### ISSUE THREAD

**Issue by andres-valdes** [prisma/nexus#147]
It would be awesome if there was a script to generate the schema instead of being strictly limited to generating as a side effect of running in development.

It could be hooked into CI or pre-commit scripts to ensure that the schema never falls out of sync with the code.

**Comment by Nayni** [comment]
It's really easy to set this up yourself, in fact we do exactly this, even in development mode the generation of the schema is separated from our server restart.

First we collect all our types:
```javascript
// schema.js
import * as QueryTypes from "./Query";
// more type imports...

export const SchemaTypes = [
  QueryTypes
];
```
Second, we define a generateSchema script:
```javascript
// generateSchema.js
import { makeSchema } from "nexus";
import { SchemaTypes } from "./schema";

makeSchema({
  types: SchemaTypes,
  outputs: {
    // outputs configs...
  },
  // anything else you need to successfully make the schema.
});
```
Third is our server.js: 
```javascript
// server.js 
const server = new ApolloServer({
  schema: makeSchema({
    tyupes: SchemaTypes,
    outputs: false // it will already be generated so let's not waste resources on this.
  })
});
```
Now everything is divided into re-usable parts, we can either use them stand-alone (for example generate the schema alone on a commit hook or during CI) or we can use them all combined. The following are a couple of example scripts: (`package.json`) 
```json
{ 
  "scripts": {
    "generate-schema": "node ./src/generateSchema.js",
    "start-dev": "node ./src/server.js",
    "generate-and-start": "yarn generate-schema && yarn start-dev",
    "dev": "nodemon yarn generate-and-start"
  }
}
```

**Comment by andres-valdes** [comment]
This is very clever! Thank you :)
