### ISSUE TITLE
New object with defaults

### ISSUE THREAD

**Issue by dizzyn** [prisma/nexus#160]
Can I create a new object with all defaults defined in the Prisma schema without saving it? I would like to create new entity, modify it and finally save. 

Schema:
`type Post {
  title: String! @default(value: "Something")
}`

Code:
````
const post = Magic_ApplyTheDefaults({});
post.title = post.title + " something else";
mutationCreatePost(post);
````

Thank you

**Comment by tgriesser** [comment]
I think this is more of a question for [nexus-prisma](https://github.com/prisma/nexus-prisma).
