### ISSUE TITLE
Circular Type Dependency

### ISSUE THREAD

**Issue by seanemmer** [prisma/nexus#18]
I'm trying to set up a simple Query resolver:

```
export const Query = prismaObjectType('Query', t => {
    t.field('listUsers', 'User', {
        list: true,
        resolve: (parent, args, ctx) => {
            return ctx.prisma.users()
        }
    })
})
```

The 'User' type referenced in the second argument is only being typechecked against 'BaseScalars', not against GenTypes.  GenTypes = GraphQLNexusGen, which as far as I can gather is populated by the nexus.ts artifact.  Is there a way to generate the nexus.ts artifact manually?  The only way mentioned in the docs is by starting the server, which I'm unable to do because the code does not pass the typechecker (User is not of type 'BaseScalars').

**Comment by tgriesser** [comment]
It looks like you're referencing the `prismaObjectType` which is part of the [nexus-prisma](https://github.com/prisma/nexus-prisma) project, a plugin for nexus. The core API is still a bit in flux, so you may want to try this out after the dust settles https://github.com/prisma/nexus-prisma/pull/78

In terms of the server restart, if you run the server in "transpile only" mode, the server will still run even if there are type errors, see how any of the [/examples](https://github.com/prisma/nexus/tree/develop/examples) npm scripts are setup. 

There still may be room for a separate CLI to run to do this for you, I'll consider adding one.
