### ISSUE TITLE
Typescript import suggests `nexus/dist`

### ISSUE THREAD

**Issue by StevenLangbroek** [prisma/nexus#189]
Hey folks!

Whenever I try to "auto import" in VS Code, it suggests imports from `nexus/dist` instead of `nexus`... Any idea why that is? If there's any more info I can provide to help debug this let me know.

Thanks!

**Comment by StevenLangbroek** [comment]
![image](https://user-images.githubusercontent.com/296796/62207277-0613bf80-b394-11e9-92c8-5ba3858596d2.png)

**Comment by jasonkuhrt** [comment]
Hey @StevenLangbroek I will try to repro this. Meanwhile if you could put up a repro repo that could help too.

**Comment by tgriesser** [comment]
This is definitely something I've experienced as well and I haven't been able to figure out the root cause. I wonder if it's because we don't have `declarationMap` enabled in the tsconfig? Or maybe we need to link to the root `index.d.ts` not the directory.
