### ISSUE TITLE
Resolve does not allow return Promise

### ISSUE THREAD

**Issue by Schubidu** [prisma/nexus#19]
Resolve does not allow Promise. 
At this example the function `context.getDocumentItem` is a Promise.
```javascript
t.field('document', {
  nullable: true,
  args: { id: idArg({ required: true }) },
  type: 'Document',
  resolve: (root, { id }, context) => {
    return context.getDocumentItem({ id });
  },
});
```

Typescript failed with this message: 
```
Error:(10, 3) TS2322: Type '(root: {}, { id }: { id: string; }, context: Context) => Promise<Document>' is not assignable to type 'FieldResolver<"Query", "document">'.
```

**Comment by Schubidu** [comment]
Type `Document` missed a field so that was my misstake.

**Comment by Maetes** [comment]
@Schubidu coan you explain what was there error on your side exactly, cause im facing exact the same but can't imagine why.
