### ISSUE TITLE
[Question]What's the difference between @prisma/nexus and nexus in package.json

### ISSUE THREAD

**Issue by zzyyzz1992** [prisma/nexus#194]
in the package.json 
```
"dependencies": {
    "@prisma/nexus": "^0.0.1",
    "nexus": "0.12.0-beta.6",
```
What's the difference between @prisma/nexus and nexus?
maybe duplicated?

**Comment by jasonkuhrt** [comment]
Hey @zzyyzz1992, the difference is temporary and soon @prisma/nexus will go away. It should only be a matter of weeks. It was a measure taken temporarily to get the nexus-prisma plugin working.
