### ISSUE TITLE
queryField for list

### ISSUE THREAD

**Issue by jeroldangarcia** [prisma/nexus#201]
What is de equivalent with queryField for this list query ?

    const Query = objectType({
      name: "Query",
      definition(t) {
        t.list.field("posts", { ....

I cannot find anything in the docs or examples.... Thank you!

**Comment by jasonkuhrt** [comment]
Hey @jeroldangarcia, I think this is what you want:

```ts
queryField("moods", {
  list: true,
  type: "String",
  resolve: () => ["happy", "sad"],
})
```
```gql
type Query {
  moods: [String!]!
}
```

**Comment by haysclark** [comment]
Update for the latest API:

```typescript
queryField("moods", {
  type: list(String),
  resolve: () => ["happy", "sad"],
})
```

```typescript
type Query {
  moods: [String!]!
}
```
