### ISSUE TITLE
TS: `compilerOptions.noErrorTruncation` option in `tsconfig.json` will hang `tsserver`

### ISSUE THREAD

**Issue by thisjeremiah** [prisma/nexus#211]
Using the option `compilerOptions.noErrorTruncation` in `tsconfig.json` will hang `tsserver` while type-checking nexus code after running typegen at least once.

Specifically, this issue occurs when type-checking resolver functions.

I will create a reproducible case if I have time, but I was hoping this might help someone else running into the same problem.

**Comment by jasonkuhrt** [comment]
Sounds like this would be a TypeScript issue. Any reason to think nexus is responsible?

**Comment by thisjeremiah** [comment]
It’s probably a TypeScript issue, but I haven’t run into this behavior using the same config on any other project. The complexity (depth?) of generated types from Nexus is seemingly causing TypeScript to hang.

We can probably close the issue, but it might be useful to leave the paper trail in case someone else tries to debug TypeScript hanging issues with Nexus.

**Comment by jasonkuhrt** [comment]
Agree we can close for now. I encourage you to report to the TS repo with a repro repo if the issue doesn’t abate though. Thanks anyways, good to have a paper trail here if ever the nexus community needs to revisit this issue.
