### ISSUE TITLE
usage of prismaObjectType from 'nexus-prisma' produces an anoying warning in vscode

### ISSUE THREAD

**Issue by kanso-git** [prisma/nexus#215]
dear all,

I am using prismaObjectType from 'nexus-prisma'
`import { prismaObjectType } from 'nexus-prisma'`

But this usage produces the following warning:
`Expression produces a union type that is too complex to represent.`

I have tried many things to fix this warning but without success.

 Any help will be appreciated.

**Comment by lewebsimple** [comment]
I got rid of the warning by specifying the model name as a string inside <> like so:
```
export const User = prismaObjectType<"User">({
  name: 'User',
  definition(t) {
    t.prismaFields(['id', 'email']);
  },
});
```

**Comment by kanso-git** [comment]
this is perfect, thank you for your valuable input
