### ISSUE TITLE
How to write a mutation arg as a list of ints

### ISSUE THREAD

**Issue by andremsantos** [prisma/nexus#27]
First of all, thank you for nexus! It's awesome!

I have this Mutation:

```
type Mutation {
    changeSupplier(productIds: [Int], supplierId: Int): Boolean
}
```

How would one represent an argument as a list of int with nexus?
The converter doesn't give the args.

```
const Mutation = objectType({
  name: "Mutation",
  definition(t) {
    t.boolean("changeSupplier", {nullable:true})
  }
})
```

Thanks!

**Comment by tgriesser** [comment]
Ah, need to fix the converter!

```ts
t.boolean("changeSupplier", {
  nullable: true,
  args: { productIds: intArg({ list: [false] }), supplierId: intArg() }
})
```

The `list: [false]` means that the list is depth 1 and can be null (false). 

```ts
list: [false, false] // [[Int]]
list: true // [Int!]
list: [true, true] // [[Int!]!]
```

**Comment by andremsantos** [comment]
Awesome. Thanks for the help.

**Comment by jasonmj** [comment]
> ```ts
> list: [false, false] // [[Int]]
> list: true // [Int!]
> list: [true, true] // [[Int!]!]
> ```

I see this issue was closed, but I'm not sure if this is documented anywhere yet. 

It seems like an appropriate place to add would be: https://nexus.js.org/docs/api-args

Am I missing it somewhere else or is there a particular location that would be most appropriate? I'm happy to submit a PR to improve the docs.

**Comment by tgriesser** [comment]
> Am I missing it somewhere else or is there a particular location that would be most appropriate? I'm happy to submit a PR to improve the docs.

That sounds like a great place to add it, a PR would be great - thanks @jasonmj!

**Comment by Chuvantinh** [comment]
Moreover, I think we can declare parameters with a list and then you can put the list of data to your mutation.
I tried with: 
```
t.nonNull.field('createTrend', {
      type: 'Trend',
      args: {
        data: nonNull(
          arg({
            type: 'TrendCreateInput',
          }),
        ),
        catId: intArg(),
        source: list(TrendSourceCreateInput)
      },
      resolve: async (_, args, context: Context) => {
        return await context.prisma.trend.create({
          data: {
            title: args.data.title,
            description: args.data.description,
            status: args.data.status,
            images: args.data.images,
            videos: args.data.videos,
            createdUser: {
              connect: { id: context.userId}
            },
            categories: {
              create: [
                  {
                    category: {
                      connect: {
                        id: args.catId
                      }
                    }
                  }
                ]
            },
            source:{
              create: [args.source]
            }
          },
        })

      },
    })
```
source: list(TrendSourceCreateInput) is equivalent [TrendSourceCreateInput] on the mutation
