### ISSUE TITLE
VSCode extension to convert SDL

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/nexus#35]
Like Markdown Preview Enhanced shows Markdown Previews on the side. This would output SDL conversion to Nexus :)

I'm talking about this icon which comes built-in with VSCode for Markdown support. Something like that for SDL would be fun 😜

<img width="218" alt="Markdown Preview Icon" src="https://user-images.githubusercontent.com/16436270/52720830-66719900-2fce-11e9-8dec-8dc535fbc9c2.png">

**Comment by tgriesser** [comment]
Sounds neat! Though I'm not sure of the utility - since you should generally only need to do the SDL -> Nexus conversion once, I'm not sure if it would be really needed as a VSCode plugin? 

If someone wants to build it though, go for it!

**Comment by deadcoder0904** [comment]
True that but as SDL conversion is already built; it'd be cool to have it as an extension.

Idk a lot of Typescript yet (learning now) so I might make it in future. Till then if anyone wants to take it, happily do so.

An NPM module extracted for SDL conversion might've been easy to make an extension with just JS.

Also, an extension might be good to convert multiple projects. Keep up the good work. Love Nexus ❤️

**Comment by tgriesser** [comment]
Cool - glad to hear you love Nexus so far! If you (or someone else) takes this on at some point let me know and I can reopen, for now I'm going to close just to clean up the issue log.

Also, [`convertSDL`](https://github.com/prisma/nexus/blob/cf1488b3924d9ac5c77df27bcc5e0ab152dacb9f/src/index.ts#L19) is exported, and all internal classes etc should be available under the exported [`core`](https://github.com/prisma/nexus/blob/cf1488b3924d9ac5c77df27bcc5e0ab152dacb9f/src/index.ts#L28) namespace so if you do want to create a converter, go for it!
