### ISSUE TITLE
Problems making updates to the schema

### ISSUE THREAD

**Issue by axelhzf** [prisma/nexus#43]
I have a simple schema like this

```
const Query = queryType({
  definition(t) {
    t.field("user", {
      type: User,
      nullable: false,
      resolve() {
        return null;
      }
    });
  }
});
```

And this give the following error because of the `nullable`

```
$ ts-node-dev src/index.ts
Using ts-node version 8.0.2, typescript version 3.3.3
[ERROR] 12:02:47 ⨯ Unable to compile TypeScript:
src/index.ts(26,7): error TS2322: Type '() => null' is not assignable to type 'FieldResolver<"Query", "user">'.
  Type 'null' is not assignable to type 'MaybePromise<{ id: MaybePromise<string>; name: MaybePromise<string>; }>'.
```

The problem is that when I update to `nullable: true` I still get the same error.
It looks like it is getting the old generated types because it cannot run the server to generate the new types.

**Comment by tgriesser** [comment]
If you run with `--transpileOnly` option it will start the server even with type errors which will then allow it to generate the correct types.

Probably need to add this to the docs/faq since this has come up a few times.

**Comment by axelhzf** [comment]
The downside about `--transpileOnly` transpile only is that it won't detect any errors.

Maybe I could setup an initial step to generate the schema using `--transpileOnly` and then run the application with error detection enabled.

**Comment by tgriesser** [comment]
Generally my workflow when developing is to have two processes running via gulp or similar, one starting/reloading the server with transpile only, one checking for errors.

Then in CI I’ll only have the `tsc` run so it catches any errors.

**Comment by axelhzf** [comment]
Ok, that makes sense. Thanks!

**Comment by jasonkuhrt** [comment]
Related https://github.com/prisma-labs/nexus/issues/77
