### ISSUE TITLE
Generated Typescript definitions for Unions are null or undefined

### ISSUE THREAD

**Issue by sgwilym** [prisma/nexus#44]
```js
const AuthSuccess = objectType({
  name: "AuthSuccess",
  definition(t) {
    t.string("token");
    t.field("user", { type: CurrentUser });
  }
});
const NoUser = objectType({
  name: "NoUser",
  definition(t) {
    t.string("message");
  }
});
const WrongPassword = objectType({
  name: "WrongPassword",
  definition(t) {
    t.string("message");
  }
});
const AuthResult = unionType({
  name: "AuthResult",
  definition(t) {
    t.members(AuthSuccess, NoUser, WrongPassword);
  }
});
const AuthPayload = objectType({
  name: "AuthPayload",
  definition(t) {
    t.field("result", { type: AuthResult });
  }
});
```

generates the following typescript definition for `AuthPayload` in `nexus.ts`:

```typescript
  AuthPayload: { // root type
    result: undefined | null; // AuthResult!
  }
```

This is the same for any other union I define. Am I doing something wrong?

And while I'm here, is there a better way to resolve types than looking at what properties a root field has? In the example above, some of the types that are part of the `AuthResult` union have exactly the same fields, and what I'm really interested in is their type identity.

**Comment by tgriesser** [comment]
> This is the same for any other union I define. Am I doing something wrong?

Nope, this is a bug. Will have a patch up shortly.

> And while I'm here, is there a better way to resolve types than looking at what properties a root field has? In the example above, some of the types that are part of the `AuthResult` union have exactly the same fields, and what I'm really interested in is their type identity.

I'm not sure I follow the question. 

Are you asking how you can choose between `WrongPassword` and `NoUser` in the union's `resolveType` given that they have the same root fields? 

The answer is to define custom types for the root field and have them picked up by the `typegenAutoConfig`. See [this comment](https://github.com/prisma/nexus/issues/36#issuecomment-463649216) for a little more explanation, though I need to add more documentation on type configuration in general.
