### ISSUE TITLE
NexusGenFieldTypes uses NexusGenRootTypes for properties

### ISSUE THREAD

**Issue by umidbekkarimov** [prisma/nexus#48]
As far as I understand we need `NexusGenRootTypes` for resolvers and `NexusGenFieldTypes` for actual results.
This how my generated file looks like:
```ts
export interface NexusGenRootTypes {
  BasketModel: {
    id: number; // Int!
    userId: number; // Int!
  };
  BasketProductModel: {
    id: number; // Int!
    price?: number | null; // Float
    productId: number; // Int!
    quantity: number; // Int!
  };
  UserModel: {
    email?: string | null; // String
    id: number; // Int!
    phone?: string | null; // String
  };
}

export interface NexusGenFieldTypes {
  BasketModel: {
    id: number; // Int!
    products: NexusGenRootTypes["BasketProductModel"][]; // [BasketProductModel!]!
    `: NexusGenRootTypes["UserModel"]; // UserModel!
    userId: number; // Int!
  };
  BasketProductModel: {
    id: number; // Int!
    price?: number | null; // Float
    productId: number; // Int!
    quantity: number; // Int!
  };
  OrderModel: {
    basket: NexusGenRootTypes["BasketModel"]; // BasketModel!
    basketId: number; // Int!
    code: string; // String!
    createdAt: any; // Date!
    customerComment: string | null; // String
    id: number; // Int!
    managerComment: string | null; // String
  };
  UserModel: {
    email?: string | null; // String
    id: number; // Int!
    phone?: string | null; // String
  };
}
```
`NexusGenFieldTypes["OrderModel"]` uses `NexusGenRootTypes["BasketModel"]` type for `basket` property and typescript does not let to access `order.basket.user` or `order.basket.products` because of that.

Is it intended to be like that? And we have to create our own types for loaded fragments?

**Comment by tgriesser** [comment]
> `NexusGenFieldTypes["OrderModel"]` uses `NexusGenRootTypes["BasketModel"]` type for `basket` property and typescript does not let to access `order.basket.user` or `order.basket.products` because of that.

Can you show an example of where/how you're accessing these? The idea with Nexus is that you generally shouldn't ever need to reference the types, they should be inferred within the queries.

Also, the generated "root" types should only be used as a fallback for types you don't otherwise have definitions for in your project you can reference. See https://github.com/prisma/nexus/issues/36#issuecomment-463649216 for more explanation here.

**Comment by tgriesser** [comment]
> Is it intended to be like that? And we have to create our own types for loaded fragments?

Also yes, generating definitions for fragments and other "execution query" types is currently out of scope for Nexus, there are already great solutions with:

https://github.com/dotansimha/graphql-code-generator
https://github.com/apollographql/apollo-tooling

Nexus focuses more on end-to-end type safety on the server

**Comment by umidbekkarimov** [comment]
> Can you show an example of where/how you're accessing these?

I have monorepo with `api`, `web` and `shared` workspaces.
Generated code goes to `shared` so I can access types from `web` like this:

```ts
export const orderModelFragment = gql`
  fragment OrderModelFragment on OrderModel {
    # takes everything 
  }
`;

export const orderModelQuery = gql`
  ${orderModelFragment}

  query OrderModelQuery($id: Int!) {
    orderModel(id: $id) {
      ...OrderModelFragment
    }
  }
`;

// { id: number }
export type OrderModelQueryInput = NexusGenArgTypes["Query"]["orderModel"];
// { orderModel: NexusGenFieldTypes["OrderModel"] }
export type OrderModelQueryResult = Pick<NexusGenFieldTypes["Query"], "orderModel">;
```

> Also yes, generating definitions for fragments and other "execution query" types is currently out of scope for Nexus, there are already great solutions with:
> 
> https://github.com/dotansimha/graphql-code-generator
> https://github.com/apollographql/apollo-tooling

Thanks for links, I was hoping to cover these features with nexus.

Anyways, thanks for your time!
