### ISSUE TITLE
XXX was already defined and imported as a type, check the docs for extending types

### ISSUE THREAD

**Issue by nikiask** [prisma/nexus#52]
If I have

```typescript
export const testArgs1 = {
  foo: idArg()
};

export const testArgs2 = {
  bar: idArg()
};
```

I get the error `Error: ID was already defined and imported as a type, check the docs for extending types`. Same with `intArg()`. Seems like you can only have 1 of each xxxArg().

**Comment by tgriesser** [comment]
That error shouldn't have anything to do with arg types, can you paste the rest of your code?

**Comment by tgriesser** [comment]
Oh actually I think I might know what it is... will investigate. Are you getting this with `nexus-prisma` or some other schema integration?

**Comment by nikiask** [comment]
Just plain nexus and apollo-server.

**Comment by tgriesser** [comment]
Can you paste the stack trace for the error? There's two places that can come from and I want to make sure I know which one it is. Also are you defining any scalars that overwrite the builtins, e.g. a custom `ID`?

**Comment by nikiask** [comment]
```
./node_modules/nexus/src/builder.ts:907
  return new Error(
         ^
Error: ID was already defined and imported as a type, check the docs for extending types
    at extendError (./node_modules/nexus/src/builder.ts:907:10)
    at SchemaBuilder.addType (./node_modules/nexus/src/builder.ts:261:13)
    at addTypes (./node_modules/nexus/src/builder.ts:948:13)
    at ./node_modules/nexus/src/builder.ts:952:41
    at Array.forEach (<anonymous>)
    at addTypes (./node_modules/nexus/src/builder.ts:952:24)
    at ./node_modules/nexus/src/builder.ts:952:41
    at Array.forEach (<anonymous>)
    at addTypes (./node_modules/nexus/src/builder.ts:952:24)
    at buildTypes (./node_modules/nexus/src/builder.ts:931:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by tgriesser** [comment]
Fixed in 0.9.16

**Comment by SagnikPradhan** [comment]
Just in case anybody is getting similar error and is on `0.35.0` use `next` instead.

**Comment by AnnuCode** [comment]
> Just in case anybody is getting similar error and is on `0.35.0` use `next` instead.

I'm facing the same issue, can you please elaborate on your answer?

**Comment by SagnikPradhan** [comment]
> > Just in case anybody is getting similar error and is on `0.35.0` use `next` instead.
> 
> I'm facing the same issue, can you please elaborate on your answer?

Use `nexus-prisma@next`
