### ISSUE TITLE
Use Prisma generated input type as arg

### ISSUE THREAD

**Issue by spencerolsen** [prisma/nexus#69]
I am trying to add my own custom mutation on top of the mutations generated by Prisma. As one of the args, I would like to use a prisma generated input type. Currently it seems that unless I create my own input type, I can only use scalars as args for my mutation? Is that correct? Still trying to get a hang of how nexus and prisma interact.

Currently, in our custom resolver definitions, we have:
`createNavigationItems(data: [NavigationItemCreateInput!]!): [NavigationItem]!`

How can I do the same thing with nexus?

```TypeScript
const Mutation = prismaObjectType({ 
  name: 'Mutation',
  definition(t) { 
    t.prismaFields(['*'])

    t.list.field('createManyNavigationItems', {
      type: 'NavigationItem',
      args: {
        data: NavigationItemCreateInput[] // THIS IS WHERE I WANT TO USE THE PRISMA GENERATED INPUT TYPE BUT IT THROWS AN ERROR
      },
      resolve(root, args, ctx, info) {
        let createdNavigationItems: NavigationItem[] = [];

        for (let navItemInput of args.data) {
          let createdNavigationItem: NavigationItem = ctx.prisma.createNavigationItem(navItemInput);
          createdNavigationItems.push(createdNavigationItem);
        }

        return createdNavigationItems;
      }
    })
  }
});
```

**Comment by Weakky** [comment]
Hey there,

Simply use the `arg` function to reference other `InputObjectType`s 🙂

**Comment by spencerolsen** [comment]
Great, thanks for the help. That worked perfectly.  👍
