### ISSUE TITLE
release: Automate the release process.

### ISSUE THREAD

**Issue by tanguyantoine** [prisma/nexus#7]
I would like to propose you to add 2 dev dependencies to automate the release process and ease respository changes communication.

These tools are: 

* commitizen : https://github.com/commitizen/cz-cli
* semantic-release: https://github.com/semantic-release/semantic-release 

**Commitizen** will ensure we are using convention whilre writing commit so that we can auto generate changelog later. more info https://www.conventionalcommits.org . It would be trivial to install it because you are already using husky hooks mechanism

**semantic release** helps deploying npm packages by automating multiples things. 
By using it, we would be able to automate the release process if in addition we use Github Actions.

`@semantice-release/changelog` is a `semantic-release` plugin and can generate a changelog based on the commit history of a repository. This auto generated changelog would eases the changes communication

What do you think?

**Comment by tgriesser** [comment]
Yeah this sounds great! If you want to open a PR adding this, that'd be awesome!

**Comment by tgriesser** [comment]
I'm also setting up a CircleCI pipeline, definitely want to make everything automated.

**Comment by tanguyantoine** [comment]
#8 add commitlint

**Comment by tanguyantoine** [comment]
I have access to github actions beta, I think I can setup it here but I guess I need to be a collaborator ^^

**Comment by tgriesser** [comment]
For now I'm going to keep doing this manually - may automate it in the future if it makes sense. Thanks for the idea though!
