### ISSUE TITLE
makePrismaSchema does not generate code due to an exception from mkdir

### ISSUE THREAD

**Issue by vsimko** [prisma/nexus#75]
I'm trying to run the `prisma-examples/typescript/graphql/` example.

I think the problem is in the following code:
https://github.com/prisma/nexus/blob/7dc2ac7aedc7992fb709ed580a13435993aeffe7/src/typegenMetadata.ts#L93

which causes:
```
{ Error: EEXIST: file already exists, mkdir '/home/test/prisma-examples/typescript/graphql/src/generated'
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/home/test/prisma-examples/typescript/graphql/src/generated' }
```

**Comment by kandros** [comment]
just noticed it, fix post a fix soon and write a test

**Comment by kandros** [comment]
looks like it throws if dir already exists in node 10.9 but not in 10.15.3

**Comment by vsimko** [comment]
my node version is however v8.15.1

**Comment by kandros** [comment]
it was anything below a specific version, not sure which exactly

**Comment by Weakky** [comment]
FYI, I fixed that issue with `nexus-prisma-generate` by simply ignoring the `EEXIST` error

https://github.com/prisma/nexus-prisma/blob/907d819b5918dd8ea135efdd332475a30ae6294d/packages/nexus-prisma-generate/src/index.ts#L83-L88
