### ISSUE TITLE
Reason: 'username' Field 'username' is not defined in the input type 'UserWhereUniqueInput'.

### ISSUE THREAD

**Issue by jblevins1991** [prisma/nexus#83]
I have an input (see below) built using nexus.

```
const UserUniqueInput = inputObjectType({
    name: 'UserWhereUniqueInput',
    definition(t) {
        t.id('id');
        t.string('username');
    }
});
```

And I ran this query

```
query ($where: UserWhereUniqueInput) {
  user(where:$where) {
    id
    username
    password
    posts {
      id
      title
      content
    }
  }
}
```

With the variables:

```
{
  "where": {
    "username": "jblevins"
  }
}
```

If I use id instead of username it works just fine. Did define my input incorrectly somwhere?

Here is the full error message.

`Error: Variable '$where' expected value of type 'UserWhereUniqueInput!' but got: {"username":"jblevins"}. Reason: 'username' Field 'username' is not defined in the input type 'UserWhereUniqueInput'. (line 1, column 8):query ($where: UserWhereUniqueInput!) {`

**Comment by Weakky** [comment]
Hey,

Could you please give us the definition of the graphql input type `UserWhereUniqueInput` from the outputted `schema.graphql` file ?

**Comment by jblevins1991** [comment]
This actually went away when using the SDL Converter. Must've been something I was doing or a lack of something I wasn't doing.
