### ISSUE TITLE
Subscriptions doesn't work when 'where' filter is applied to node field

### ISSUE THREAD

**Issue by nevescode** [prisma/nexus#94]
When I try to subscribe using a where filter applied to a node field my subscription doesn't receive any updates.

The same query works directly on prisma server playground but when I use nexus subscriptionField I don't get the same behavior.

Mutation:
![Screen Shot 2019-03-22 at 12 46 33 PM](https://user-images.githubusercontent.com/875888/54835232-7f8df980-4ca0-11e9-8ed5-05a1580d0f8b.png)

Prisma server playground query that works:
![Screen Shot 2019-03-22 at 12 47 19 PM](https://user-images.githubusercontent.com/875888/54835282-90d70600-4ca0-11e9-8037-9359749bf994.png)

Yoga playground query (not working):
![Screen Shot 2019-03-22 at 12 48 02 PM](https://user-images.githubusercontent.com/875888/54835340-ab10e400-4ca0-11e9-8a46-42b40414e865.png)

Code:
![Screen Shot 2019-03-22 at 1 01 41 PM](https://user-images.githubusercontent.com/875888/54836248-9c2b3100-4ca2-11e9-941c-f20a21e78025.png)

Prisma client generated code seems ok:
![Screen Shot 2019-03-22 at 12 57 08 PM](https://user-images.githubusercontent.com/875888/54835986-0a232880-4ca2-11e9-9964-2281770d6531.png)

If I remove the node>conversation>id filter the query works. Any suggestions?

**Comment by nevescode** [comment]
@tgriesser can you help me with this one?

**Comment by tgriesser** [comment]
This might be better asked in https://github.com/prisma/nexus-prisma, I don't know a whole lot about how the subscriptions are supposed to work here.

**Comment by gauthierrodaro** [comment]
@nevescode I manage to make it work in my project.

I think you have an argument issue. it should be 
```
return prisma.$subscribe.message(where)
```
instead of
```
return prisma.$subscribe.message({where})
```
