### ISSUE TITLE
extendType that is not a Query, Mutation or Input

### ISSUE THREAD

**Issue by otrebu** [prisma/nexus#95]
Hi there!

I haven't seen any example of using `extendType` like this:

```javascript
export const BasketTotal = extendType({
    type: "Basket",
    definition: t => {
        t.field("total", {
            type: "Float",
            resolve: (parent, args, ctx) => {
                // ...
            }
        });
    }
});
```

I tried it, but the resolver is not running at all. The graphql schema does get extended!

Should this be possible?

Cheers

**Comment by otrebu** [comment]
Answering to myself, it is possible, but probably not possible on a remote schema you are stitching.

**Comment by tgriesser** [comment]
Yep - not yet, working on something for that

**Comment by otrebu** [comment]
@tgriesser hope not too quickly now 😛 I am just changing the entire architecture of the application because stitching/delegation was causing too much pain.
