### ISSUE TITLE
Use custom input type as arg and interface

### ISSUE THREAD

**Issue by spencerolsen** [prisma/nexus#97]
I would like to use a custom input type that I have defined as the input type for one of the args on my custom mutation, instead of using one defined by Prisma.

Here is the custom input type I have defined:
```
export const navigationItemOverrideInput = inputObjectType({
  name: 'NavigationItemOverrideInput',
  definition(t: any): any {
    t.id("id", { required: true })
    t.int("sortOrder")
    t.string("icon")
    t.boolean("visible")
    t.boolean("newTab")
    t.field("role", {type: connectInput})
  }
});
```

Here is the mutation I am adding:
```
export const mutation = prismaObjectType({
  name: 'Mutation',
  definition(t: any): any {
    t.prismaFields(allowedPrismaOperations.mutations)

    t.list.field('upsertNavigationItemOverrides', {
      type: 'NavigationItemOverride',
      args: {
        data: arg({ type: navigationItemOverrideInput, list: true})
      },
      resolve: async(root: any, args: { data: NavigationItemOverrideInput[] }, ctx: Prisma, info: any): Promise<NavigationItemOverride[]> => {
        
      }
    });
```

In the resolve function, I get an error because there is no interface for NavigationItemOverrideInput. Is there a way to do this without creating an interface? I would hate to have to maintain both the inputObjectType and the Interface every time we make a change. Is there a better way to approach this altogether?

**Comment by tgriesser** [comment]
> I get an error because there is no interface for NavigationItemOverrideInput.

Are you referring to the term `interface` in regards to GraphQL or TypeScript?

Also, you shouldn't need to define types for the parameters of resolve, that's the idea of nexus, it should automatically infer them for you.

**Comment by spencerolsen** [comment]
Interface in regards to TypeScript. Does the return type need to be defined, or is that inferred as well?
